version: '3.3'

services:
  app:
    build:
      context: ./app/.
    container_name: "app"
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    ports:
      - "80:80"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis-vol:/data
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
         
volumes:
  redis-vol: